name: wolfSSHd Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          repository: wolfSSL/wolfssl.git
          ref: master
    - name: build wolfSSL
      run: ./autogen.sh && ./configure --enable-all --prefix=/usr && make && sudo make install
    - uses: actions/checkout@v2
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --enable-all CPPFLAGS=-DWOLFSSH_NO_FPKI
    - name: make
      run: make
    - name: make check
      run: make check
    - name: run wolfSSHd tests
      run: sudo ./run_all_sshd_tests.sh
      working-directory: ./apps/wolfsshd/test
